# Generated by Django 6.0.1 on 2026-03-22 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('registration_deadline', models.DateTimeField()),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('min_tier', models.CharField(default='Bronze', max_length=50)),
                ('max_participants', models.IntegerField(default=100)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('first_place_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('second_place_percentage', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('third_place_percentage', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('challenges', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tournaments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankings', models.JSONField(default=list)),
                ('prize_distribution', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournament_leaderboards',
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('challenges_completed', models.IntegerField(default=0)),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('prize_won', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_winner', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tournament_participations',
                'ordering': ['-score', 'total_time'],
            },
        ),
        migrations.CreateModel(
            name='TournamentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_index', models.IntegerField()),
                ('answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tournaments.tournamentparticipation')),
            ],
            options={
                'db_table': 'tournament_submissions',
                'ordering': ['challenge_index', 'submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['status', 'start_time'], name='tournaments_status_0ec904_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['difficulty', 'status'], name='tournaments_difficu_b80f71_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentparticipation',
            unique_together={('tournament', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='tournamentsubmission',
            unique_together={('participation', 'challenge_index')},
        ),
    ]
