# Generated by Django 4.2.7 on 2026-09-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_add_media_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='firebase_media_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
