# Generated by Django 6.0.1 on 2026-03-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paystack', 'Paystack'), ('tingg', 'Tingg/Cellulant'), ('lemonsqueezy', 'Lemonsqueezy'), ('paypal', 'PayPal'), ('pawapay', 'PawaPay')], max_length=20),
        ),
    ]
