# Generated by Django 4.2.11 on 2026-05-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_wallet_transaction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_wallet__efd4a5_idx',
            old_name='transaction_wallet__idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_transac_ddda52_idx',
            old_name='transaction_type_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('ZMW', 'Zambian Kwacha'), ('GHS', 'Ghanaian Cedi'), ('NGN', 'Nigerian Naira'), ('ZAR', 'South African Rand')], default='ZMW', max_length=3),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('ZMW', 'Zambian Kwacha'), ('GHS', 'Ghanaian Cedi'), ('NGN', 'Nigerian Naira'), ('ZAR', 'South African Rand')], default='ZMW', max_length=3),
        ),
    ]
