# Generated by Django 4.2.7 on 2026-06-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentauditlog_withdrawallimit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentauditlog',
            new_name='payment_aud_payment_756172_idx',
            old_name='audit_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentauditlog',
            new_name='payment_aud_withdra_6a9472_idx',
            old_name='audit_withdrawal_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentauditlog',
            new_name='payment_aud_user_id_7e9e0a_idx',
            old_name='audit_user_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentauditlog',
            new_name='payment_aud_action_12e410_idx',
            old_name='audit_action_idx',
        ),
    ]
