# Generated by Django 4.2.7 on 2026-07-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='stories/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='media_url',
            field=models.URLField(blank=True),
        ),
    ]
