# Generated by Django 4.2.11 on 2026-05-24 21:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='medium', max_length=20)),
                ('time_limit', models.IntegerField(help_text='Time limit in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('min_word_count', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_word_count', models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(1)])),
                ('submission_rules', models.JSONField(default=list, help_text='List of submission rules')),
                ('creativity_weight', models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('relevance_weight', models.IntegerField(default=35, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('detail_weight', models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_points', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_points', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('submission_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeLeaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('top_submissions', models.JSONField(default=list, help_text='Cached top 10 submissions')),
                ('total_participants', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('average_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('highest_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='challenges.challenge')),
            ],
            options={
                'db_table': 'challenge_leaderboards',
            },
        ),
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interpretation', models.TextField()),
                ('word_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('scored', 'Scored'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('creativity_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('relevance_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('detail_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('submission_time_seconds', models.IntegerField(help_text='Time taken to submit in seconds')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenge_submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['challenge', 'user'], name='challenge_s_challen_58a385_idx'), models.Index(fields=['status'], name='challenge_s_status_171c35_idx'), models.Index(fields=['submitted_at'], name='challenge_s_submitt_3adbe4_idx')],
                'unique_together': {('challenge', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('submission', 'New Submission'), ('score_update', 'Score Updated'), ('milestone', 'Milestone Reached'), ('leaderboard_change', 'Leaderboard Change')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenge_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['challenge', 'created_at'], name='challenge_a_challen_1bea14_idx'), models.Index(fields=['user', 'created_at'], name='challenge_a_user_id_02bdb4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['status', 'ends_at'], name='challenges_status_83769b_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['difficulty'], name='challenges_difficu_50023d_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['created_at'], name='challenges_created_f9a3e1_idx'),
        ),
    ]
