# Generated by Django 6.0.1 on 2026-03-22 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tag', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='alliance_logos/')),
                ('is_public', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('min_tier', models.CharField(default='Bronze', max_length=50)),
                ('max_members', models.IntegerField(default=50)),
                ('total_prestige', models.IntegerField(default=0)),
                ('tournament_wins', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_alliances', to=settings.AUTH_USER_MODEL)),
                ('officers', models.ManyToManyField(blank=True, related_name='officer_alliances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alliances',
                'ordering': ['-total_prestige', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllianceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('member_joined', 'Member Joined'), ('member_left', 'Member Left'), ('member_promoted', 'Member Promoted'), ('member_demoted', 'Member Demoted'), ('tournament_win', 'Tournament Win'), ('level_up', 'Alliance Level Up'), ('challenge_completed', 'Challenge Completed')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alliances.alliance')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alliance_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllianceInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='alliances.alliance')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_alliance_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alliance_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alliance_invitations',
                'ordering': ['-created_at'],
                'unique_together': {('alliance', 'invited_user')},
            },
        ),
        migrations.CreateModel(
            name='AllianceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('banned', 'Banned')], default='pending', max_length=20)),
                ('role', models.CharField(choices=[('member', 'Member'), ('officer', 'Officer'), ('leader', 'Leader')], default='member', max_length=20)),
                ('prestige_contributed', models.IntegerField(default=0)),
                ('tournaments_participated', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='alliances.alliance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alliance_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alliance_memberships',
                'ordering': ['-prestige_contributed', '-joined_at'],
                'unique_together': {('alliance', 'user')},
            },
        ),
    ]
