# Generated by Django 4.2.7 on 2026-06-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_security_fields_and_auth_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginhistory',
            new_name='login_histo_user_id_9416b0_idx',
            old_name='lh_user_idx',
        ),
        migrations.RenameIndex(
            model_name='loginhistory',
            new_name='login_histo_ip_addr_33bb71_idx',
            old_name='lh_ip_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
